# Default values for admin-map.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

adminmap_namespace: "adminmap"

adminmap:
  image:
    repository: willnilges/network-map
    tag: admin-helm
    pullPolicy: Always
  port: 3000

nameOverride: ""
fullnameOverride: ""

podAnnotations: {}
podLabels: {}

resources: {}

livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http

nodeSelector: {}

tolerations: []

affinity: {}
