version: '3.8'
services:
  admin-map:
    container_name: admin-map
    build: .
    environment:
      - NODE_ENV=production
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - admin-map
    expose:
      - 3000
    labels:
      - "traefik.enable=true"
      - "traefik.port=80"
        # .nycmesh.net URL (with HTTPS)
      - "traefik.http.routers.admin-map.rule=Host(`admin-map.grandsvc.mesh.nycmesh.net`)"
      - "traefik.http.routers.admin-map.entrypoints=websecure"
      - "traefik.http.routers.admin-map.tls=true"
      - "traefik.http.routers.admin-map.tls.certresolver=grandsvcresolver"
        # .nycmesh.net Redirect insecure traffic
      - "traefik.http.routers.admin-map-insecure.rule=Host(`admin-map.grandsvc.mesh.nycmesh.net`)"
      - "traefik.http.routers.admin-map-insecure.entrypoints=web"
      - "traefik.http.middlewares.admin-map-https.redirectscheme.scheme=https"
      - "traefik.http.routers.admin-map-insecure.middlewares=admin-map-https@docker"
        # .mesh URL
      - "traefik.http.routers.admin-map-mesh.rule=Host(`admin-map.grandsvc.mesh`)"
      - "traefik.http.routers.admin-map-mesh.entrypoints=web"

networks:
  admin-map:
    external: true
    name: traefik-net
