apiVersion: v1
kind: Secret
metadata:
  name: pull-secret
  namespace: {{ .Values.adminmap_namespace }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
