apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "map.fullname" . }}
  namespace: {{ .Values.map_namespace }}
  labels:
    {{- include "map.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "map.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: map
        {{- include "map.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.map.image.repository }}:{{ .Values.map.image.tag }}"
          imagePullPolicy: {{ .Values.map.image.pullPolicy }}
          env:
            - name: NODE_ENV
              value: production
          ports:
            - name: http
              containerPort: {{ .Values.map.port }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}