name: Publish Docker Image

on:
  push:
    branches:
      - meshdb

jobs:
  push_to_registry:
    name: Push Docker Image to Docker Hub
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/meshdb'
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      
      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: willnilges/network-map

      - name: Build and push Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: "willnilges/network-map:helm"
          #tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  deploy_to_dev3:
    name: Deploy to dev 3
    uses: ./.github/workflows/helm-deploy.yaml
    with:
      environment: dev3
    secrets: inherit
    if: github.ref == 'refs/heads/meshdb'
    needs: push_to_registry

  deploy_to_prod1:
    name: Deploy to prod 1
    uses: ./.github/workflows/helm-deploy.yaml
    with:
      environment: prod1
    secrets: inherit
    if: github.ref == 'refs/heads/meshdb'
    needs: deploy_to_dev3
  
  deploy_to_prod2:
    name: Deploy to prod 2
    uses: ./.github/workflows/helm-deploy.yaml
    with:
      environment: prod2
    secrets: inherit
    if: github.ref == 'refs/heads/meshdb'
    needs: deploy_to_prod1
