name: Publish and Deploy

on:
  push:
    branches:
      #- meshdb
      - meshdb-admin

jobs:
  # Dev and Prod use the same image
  push_to_registry_prod:
    name: Push to prod
    uses: ./.github/workflows/build-push-image.yaml
    with:
      environment: prod2
      image_tag: willnilges/network-map:admin-helm
    secrets: inherit
    if: github.ref == 'refs/heads/meshdb-admin'

  deploy_to_dev3:
    name: Deploy to dev 3
    uses: ./.github/workflows/helm-deploy.yaml
    with:
      environment: dev3
      imageTag: admin-helm
    secrets: inherit
    if: github.ref == 'refs/heads/meshdb-admin'
    needs: push_to_registry_prod

  deploy_to_prod1:
    name: Deploy to prod 1
    uses: ./.github/workflows/helm-deploy.yaml
    needs: deploy_to_dev3
    with:
      environment: prod1
      imageTag: admin-helm
    secrets: inherit
    if: github.ref == 'refs/heads/meshdb-admin'
  
  deploy_to_prod2:
    name: Deploy to prod 2
    uses: ./.github/workflows/helm-deploy.yaml
    needs: deploy_to_prod1
    with:
      environment: prod2
      imageTag: admin-helm
    secrets: inherit
    if: github.ref == 'refs/heads/meshdb-admin'
